// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bmadServer.ApiService.Data;

#nullable disable

namespace bmadServer.ApiService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127151644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.AgentMessageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceAgent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TargetAgent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("agent_message_logs", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.BufferedInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConflictId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConflictId");

                    b.HasIndex("WorkflowInstanceId", "FieldName", "IsApplied");

                    b.ToTable("buffered_inputs", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Conflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscalationRetries")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inputs");

                    b.Property<string>("ResolutionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("conflicts", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.ConflictRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Configuration")
                        .HasColumnType("jsonb");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ConflictRules");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Context")
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecisionMakerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("LockReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedBy")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Options")
                        .HasColumnType("jsonb");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Value")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecisionMakerId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Decision1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Decision2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DecisionId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DecisionId2")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OverrideJustification")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResolverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Decision1Id");

                    b.HasIndex("Decision2Id");

                    b.HasIndex("ResolverId");

                    b.ToTable("DecisionConflicts");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewerIds")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("RequesterId");

                    b.ToTable("decision_reviews", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionReviewResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("decision_review_responses", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Context")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Options")
                        .HasColumnType("jsonb");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Value")
                        .HasColumnType("jsonb");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ModifierId");

                    b.ToTable("decision_versions", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonaSwitchCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionPersona")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkflowState")
                        .HasColumnType("jsonb");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowState");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WorkflowState"), "gin");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Session_Expiry", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.TranslationMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessTerm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TechnicalTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TechnicalTerm")
                        .IsUnique();

                    b.ToTable("translation_mappings", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PersonaType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "Role");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.AgentHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FromAgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToAgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkflowStepId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowInstanceId", "Timestamp");

                    b.ToTable("agent_handoffs", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("ModifiedResponse")
                        .HasColumnType("text");

                    b.Property<string>("ProposedResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reasoning")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.QueuedInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Queued");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "gin");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_queued_inputs_user");

                    b.HasIndex("WorkflowId", "Status", "SequenceNumber")
                        .HasDatabaseName("idx_queued_inputs_workflow_status");

                    b.ToTable("queued_inputs", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckpointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("StateSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TriggeredBy")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Metadata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("StateSnapshot");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StateSnapshot"), "gin");

                    b.HasIndex("TriggeredBy");

                    b.HasIndex("WorkflowId", "CreatedAt")
                        .HasDatabaseName("idx_checkpoints_workflow_time");

                    b.HasIndex("WorkflowId", "Version")
                        .HasDatabaseName("idx_checkpoints_version");

                    b.ToTable("workflow_checkpoints", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternativesConsidered")
                        .HasColumnType("jsonb");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InputType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlternativesConsidered");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AlternativesConsidered"), "gin");

                    b.HasIndex("Payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("idx_workflow_events_user_time");

                    b.ToTable("workflow_events", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedContextJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("shared_context");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledAt");

                    b.HasIndex("Context");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Context"), "gin");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PausedAt");

                    b.HasIndex("SharedContextJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SharedContextJson"), "gin");

                    b.HasIndex("Status");

                    b.HasIndex("StepData");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StepData"), "gin");

                    b.HasIndex("UserId");

                    b.ToTable("workflow_instances", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowId", "UserId")
                        .IsUnique();

                    b.ToTable("workflow_participants", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowStepHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Input")
                        .HasColumnType("jsonb");

                    b.Property<string>("Output")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Input");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Input"), "gin");

                    b.HasIndex("Output");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Output"), "gin");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("StepId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("workflow_step_histories", (string)null);
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.AgentMessageLog", b =>
                {
                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.BufferedInput", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.Conflict", "Conflict")
                        .WithMany()
                        .HasForeignKey("ConflictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("bmadServer.ApiService.Data.Entities.Workflow", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conflict");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Conflict", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.Workflow", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Decision", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "DecisionMaker")
                        .WithMany()
                        .HasForeignKey("DecisionMakerId");

                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionMaker");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionConflict", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.Decision", "Decision1")
                        .WithMany()
                        .HasForeignKey("Decision1Id");

                    b.HasOne("bmadServer.ApiService.Data.Entities.Decision", "Decision2")
                        .WithMany()
                        .HasForeignKey("Decision2Id");

                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolverId");

                    b.Navigation("Decision1");

                    b.Navigation("Decision2");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionReview", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.Decision", "Decision")
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.Navigation("Decision");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionReviewResponse", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.DecisionReview", "Review")
                        .WithMany("Responses")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionVersion", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.Decision", "Decision")
                        .WithMany("Versions")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "Modifier")
                        .WithMany()
                        .HasForeignKey("ModifierId");

                    b.Navigation("Decision");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Session", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.UserRole", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.AgentHandoff", b =>
                {
                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.ApprovalRequest", b =>
                {
                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.QueuedInput", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowCheckpoint", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriggeredByUser");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowEvent", b =>
                {
                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowParticipant", b =>
                {
                    b.HasOne("bmadServer.ApiService.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("bmadServer.ApiService.Models.Workflows.WorkflowStepHistory", b =>
                {
                    b.HasOne("bmadServer.ApiService.Models.Workflows.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.Decision", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.DecisionReview", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("bmadServer.ApiService.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
