using bmadServer.ApiService.Models.Workflows;
using Xunit;

namespace bmadServer.Tests.Unit.Models;

public class QueuedInputTests
{
    [Fact]
    public void QueuedInput_Should_Initialize_With_Default_Values()
    {
        // Arrange & Act
        var input = new QueuedInput();

        // Assert
        Assert.Equal(Guid.Empty, input.Id); // ID will be generated by DB
        Assert.Equal(string.Empty, input.InputType);
        Assert.Equal(InputStatus.Queued, input.Status);
        Assert.True(input.QueuedAt <= DateTime.UtcNow);
        Assert.Null(input.ProcessedAt);
        Assert.Null(input.RejectionReason);
        Assert.Equal(0, input.SequenceNumber);
    }

    [Fact]
    public void InputStatus_Should_Have_Four_Values()
    {
        // Assert
        Assert.Equal(4, Enum.GetValues<InputStatus>().Length);
        Assert.True(Enum.IsDefined(typeof(InputStatus), InputStatus.Queued));
        Assert.True(Enum.IsDefined(typeof(InputStatus), InputStatus.Processed));
        Assert.True(Enum.IsDefined(typeof(InputStatus), InputStatus.Rejected));
        Assert.True(Enum.IsDefined(typeof(InputStatus), InputStatus.Failed));
    }

    [Fact]
    public void QueuedInput_Should_Set_All_Properties()
    {
        // Arrange
        var workflowId = Guid.NewGuid();
        var userId = Guid.NewGuid();
        var inputType = "message";

        // Act
        var input = new QueuedInput
        {
            WorkflowId = workflowId,
            UserId = userId,
            InputType = inputType,
            Status = InputStatus.Processed,
            ProcessedAt = DateTime.UtcNow,
            SequenceNumber = 1L
        };

        // Assert
        Assert.Equal(workflowId, input.WorkflowId);
        Assert.Equal(userId, input.UserId);
        Assert.Equal(inputType, input.InputType);
        Assert.Equal(InputStatus.Processed, input.Status);
        Assert.NotNull(input.ProcessedAt);
        Assert.Equal(1L, input.SequenceNumber);
    }

    [Fact]
    public void QueuedInput_Should_Track_Rejection()
    {
        // Arrange
        var input = new QueuedInput
        {
            Status = InputStatus.Rejected,
            RejectionReason = "Invalid input format"
        };

        // Assert
        Assert.Equal(InputStatus.Rejected, input.Status);
        Assert.Equal("Invalid input format", input.RejectionReason);
    }
}
