using bmadServer.ApiService.Models.Workflows;
using Xunit;

namespace bmadServer.Tests.Unit.Models;

public class WorkflowCheckpointTests
{
    [Fact]
    public void WorkflowCheckpoint_Should_Initialize_With_Default_Values()
    {
        // Arrange & Act
        var checkpoint = new WorkflowCheckpoint();

        // Assert
        Assert.Equal(Guid.Empty, checkpoint.Id); // ID will be generated by DB
        Assert.Equal(string.Empty, checkpoint.StepId);
        Assert.Equal(CheckpointType.StepCompletion, checkpoint.CheckpointType);
        Assert.Equal(0, checkpoint.Version);
        Assert.True(checkpoint.CreatedAt <= DateTime.UtcNow);
    }

    [Fact]
    public void CheckpointType_Should_Have_Four_Values()
    {
        // Assert
        Assert.Equal(4, Enum.GetValues<CheckpointType>().Length);
        Assert.True(Enum.IsDefined(typeof(CheckpointType), CheckpointType.StepCompletion));
        Assert.True(Enum.IsDefined(typeof(CheckpointType), CheckpointType.DecisionConfirmation));
        Assert.True(Enum.IsDefined(typeof(CheckpointType), CheckpointType.AgentHandoff));
        Assert.True(Enum.IsDefined(typeof(CheckpointType), CheckpointType.ExplicitSave));
    }

    [Fact]
    public void WorkflowCheckpoint_Should_Set_All_Properties()
    {
        // Arrange
        var workflowId = Guid.NewGuid();
        var triggeredBy = Guid.NewGuid();
        var stepId = "step-1";
        var version = 1L;

        // Act
        var checkpoint = new WorkflowCheckpoint
        {
            WorkflowId = workflowId,
            StepId = stepId,
            CheckpointType = CheckpointType.DecisionConfirmation,
            Version = version,
            TriggeredBy = triggeredBy
        };

        // Assert
        Assert.Equal(workflowId, checkpoint.WorkflowId);
        Assert.Equal(stepId, checkpoint.StepId);
        Assert.Equal(CheckpointType.DecisionConfirmation, checkpoint.CheckpointType);
        Assert.Equal(version, checkpoint.Version);
        Assert.Equal(triggeredBy, checkpoint.TriggeredBy);
    }
}
