// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace bmadServer.BDD.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SignalRHubSetupWebSocketConnectionStory3_1Feature : object, Xunit.IClassFixture<SignalRHubSetupWebSocketConnectionStory3_1Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "SignalR Hub Setup & WebSocket Connection (Story 3-1)", ("  As a user\n  I want to establish a persistent WebSocket connection to bmadServer" +
                "\n  So that I can receive real-time updates and send messages without page refres" +
                "hes"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "3-1-signalr-hub.feature"
#line hidden
        
        public SignalRHubSetupWebSocketConnectionStory3_1Feature(SignalRHubSetupWebSocketConnectionStory3_1Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the API is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("I have a valid JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Establish WebSocket connection with valid JWT")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Establish WebSocket connection with valid JWT")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "websocket")]
        public async System.Threading.Tasks.Task EstablishWebSocketConnectionWithValidJWT()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "websocket"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Establish WebSocket connection with valid JWT", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("I connect to SignalR hub \"/chathub\" with JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("the connection is established successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
    await testRunner.AndAsync("OnConnectedAsync is called on the server", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("the connection ID is logged", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Send message via SignalR")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Send message via SignalR")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "websocket")]
        public async System.Threading.Tasks.Task SendMessageViaSignalR()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "websocket"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Send message via SignalR", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("I am connected to the SignalR hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("I invoke \"SendMessage\" with message \"Hello from test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("the server receives the message within 100ms", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 22
    await testRunner.AndAsync("the message is acknowledged within 2 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Join workflow room")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Join workflow room")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "websocket")]
        public async System.Threading.Tasks.Task JoinWorkflowRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "websocket"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Join workflow room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.GivenAsync("I am connected to the SignalR hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.WhenAsync("I invoke \"JoinWorkflow\" with workflowId \"test-workflow-123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("I am added to the workflow group", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
    await testRunner.AndAsync("I can receive workflow-specific messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Leave workflow room")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Leave workflow room")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "websocket")]
        public async System.Threading.Tasks.Task LeaveWorkflowRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "websocket"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Leave workflow room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.GivenAsync("I am connected to the SignalR hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
    await testRunner.AndAsync("I have joined workflow \"test-workflow-123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.WhenAsync("I invoke \"LeaveWorkflow\" with workflowId \"test-workflow-123\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("I am removed from the workflow group", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Automatic reconnection after connection drop")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Automatic reconnection after connection drop")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "reconnection")]
        public async System.Threading.Tasks.Task AutomaticReconnectionAfterConnectionDrop()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "reconnection"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Automatic reconnection after connection drop", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 40
    await testRunner.GivenAsync("I am connected to the SignalR hub", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.WhenAsync("the WebSocket connection drops unexpectedly", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("SignalR attempts reconnection with exponential backoff", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
    await testRunner.AndAsync("the connection is re-established", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync("session recovery flow executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Connection rejected with invalid JWT")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Connection rejected with invalid JWT")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "authentication")]
        public async System.Threading.Tasks.Task ConnectionRejectedWithInvalidJWT()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "authentication"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Connection rejected with invalid JWT", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 48
    await testRunner.WhenAsync("I attempt to connect to SignalR hub with invalid JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("the connection is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("I receive an authentication error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Connection rejected without JWT")]
        [Xunit.TraitAttribute("FeatureTitle", "SignalR Hub Setup & WebSocket Connection (Story 3-1)")]
        [Xunit.TraitAttribute("Description", "Connection rejected without JWT")]
        [Xunit.TraitAttribute("Category", "realtime")]
        [Xunit.TraitAttribute("Category", "signalr")]
        [Xunit.TraitAttribute("Category", "authentication")]
        public async System.Threading.Tasks.Task ConnectionRejectedWithoutJWT()
        {
            string[] tagsOfScenario = new string[] {
                    "realtime",
                    "signalr",
                    "authentication"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Connection rejected without JWT", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.WhenAsync("I attempt to connect to SignalR hub without JWT token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the connection is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("I receive an authentication error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await SignalRHubSetupWebSocketConnectionStory3_1Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await SignalRHubSetupWebSocketConnectionStory3_1Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
