// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace bmadServer.BDD.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Mobile_ResponsiveChatInterfaceStory3_6Feature : object, Xunit.IClassFixture<Mobile_ResponsiveChatInterfaceStory3_6Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "Mobile-Responsive Chat Interface (Story 3-6)", ("  As a user on mobile\n  I want the chat interface to work seamlessly on my phone\n" +
                "  So that I can approve decisions and monitor workflows on the go"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "3-6-mobile-responsive.feature"
#line hidden
        
        public Mobile_ResponsiveChatInterfaceStory3_6Feature(Mobile_ResponsiveChatInterfaceStory3_6Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("I am accessing bmadServer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("I am authenticated", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Mobile layout adapts below 768px")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Mobile layout adapts below 768px")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "responsive")]
        public async System.Threading.Tasks.Task MobileLayoutAdaptsBelow768Px()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "responsive"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mobile layout adapts below 768px", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("I access the chat on a mobile device (< 768px width)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("the layout adapts to single-column", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
    await testRunner.AndAsync("the sidebar is collapsed to a hamburger menu", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("the chat takes full width", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("all content is readable without horizontal scroll", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full-width input on mobile")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Full-width input on mobile")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "input")]
        public async System.Threading.Tasks.Task Full_WidthInputOnMobile()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "input"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Full-width input on mobile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("I am on a mobile device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("I view the chat input area", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("the input expands to full width", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("the Send button is at least 44px in size", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("all tap targets are at least 44px (WCAG 2.1 AA)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Mobile input expands to 48px minimum")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Mobile input expands to 48px minimum")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "input")]
        public async System.Threading.Tasks.Task MobileInputExpandsTo48PxMinimum()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "input"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mobile input expands to 48px minimum", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.GivenAsync("I am on a mobile device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
    await testRunner.WhenAsync("I interact with the chat input", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
    await testRunner.ThenAsync("all touch targets are at least 48px", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
    await testRunner.AndAsync("buttons are easily tappable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("no accidental taps occur", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Virtual keyboard handling")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Virtual keyboard handling")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "keyboard")]
        public async System.Threading.Tasks.Task VirtualKeyboardHandling()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "keyboard"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Virtual keyboard handling", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.GivenAsync("I am on a mobile device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
    await testRunner.WhenAsync("the virtual keyboard appears", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the chat scrolls to keep the input visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.AndAsync("the input stays fixed at the bottom", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("previous messages remain accessible above", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Chat adjusts for keyboard height")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Chat adjusts for keyboard height")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "keyboard")]
        public async System.Threading.Tasks.Task ChatAdjustsForKeyboardHeight()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "keyboard"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Chat adjusts for keyboard height", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.GivenAsync("I am typing a message on mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.AndAsync("the virtual keyboard is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.WhenAsync("I scroll the chat", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("the visible area adjusts for keyboard height", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("I can still see recent messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.AndAsync("the input remains accessible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Swipe down to refresh")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Swipe down to refresh")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "gestures")]
        public async System.Threading.Tasks.Task SwipeDownToRefresh()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "gestures"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Swipe down to refresh", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.GivenAsync("I am on a mobile device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
    await testRunner.WhenAsync("I swipe down on the chat", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the chat refreshes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("the latest messages are loaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("a refresh indicator is shown", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tap and hold to copy message")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Tap and hold to copy message")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "gestures")]
        public async System.Threading.Tasks.Task TapAndHoldToCopyMessage()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "gestures"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tap and hold to copy message", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 61
    await testRunner.GivenAsync("I am viewing a message on mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.WhenAsync("I tap and hold on the message", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("a context menu appears", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("I can copy the message text", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("I can perform other message actions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Swipe to dismiss notifications")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Swipe to dismiss notifications")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "gestures")]
        public async System.Threading.Tasks.Task SwipeToDismissNotifications()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "gestures"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Swipe to dismiss notifications", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 69
    await testRunner.GivenAsync("I receive a notification on mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
    await testRunner.WhenAsync("I swipe the notification", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the notification is dismissed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.AndAsync("it does not reappear", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="VoiceOver support on iOS")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "VoiceOver support on iOS")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "accessibility")]
        [Xunit.TraitAttribute("Category", "screenreader")]
        public async System.Threading.Tasks.Task VoiceOverSupportOnIOS()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "accessibility",
                    "screenreader"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("VoiceOver support on iOS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 76
    await testRunner.GivenAsync("I am using VoiceOver on iOS", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.WhenAsync("I navigate the chat interface", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("all interactive elements are announced", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
    await testRunner.AndAsync("gestures work with VoiceOver enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.AndAsync("messages have proper ARIA labels", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
    await testRunner.AndAsync("focus order is logical", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TalkBack support on Android")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "TalkBack support on Android")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "accessibility")]
        [Xunit.TraitAttribute("Category", "screenreader")]
        public async System.Threading.Tasks.Task TalkBackSupportOnAndroid()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "accessibility",
                    "screenreader"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TalkBack support on Android", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 85
    await testRunner.GivenAsync("I am using TalkBack on Android", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
    await testRunner.WhenAsync("I navigate the chat interface", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("all interactive elements are announced", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 88
    await testRunner.AndAsync("gestures work with TalkBack enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.AndAsync("the chat is fully navigable by touch", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
    await testRunner.AndAsync("proper content descriptions are provided", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reduced motion preference")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Reduced motion preference")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "accessibility")]
        [Xunit.TraitAttribute("Category", "motion")]
        public async System.Threading.Tasks.Task ReducedMotionPreference()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "accessibility",
                    "motion"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reduced motion preference", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 94
    await testRunner.GivenAsync("I have enabled reduced motion preference", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.WhenAsync("animations would normally play", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.ThenAsync("animations are disabled or significantly reduced", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
    await testRunner.AndAsync("scroll behavior is instant instead of smooth", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.AndAsync("no motion-triggered discomfort occurs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Respect prefers-reduced-motion CSS")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Respect prefers-reduced-motion CSS")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "accessibility")]
        [Xunit.TraitAttribute("Category", "motion")]
        public async System.Threading.Tasks.Task RespectPrefers_Reduced_MotionCSS()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "accessibility",
                    "motion"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Respect prefers-reduced-motion CSS", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
    await testRunner.GivenAsync("my system has \"prefers-reduced-motion: reduce\" set", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
    await testRunner.WhenAsync("I interact with the chat", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
    await testRunner.ThenAsync("CSS animations respect the preference", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 105
    await testRunner.AndAsync("transitions are instant or minimal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
    await testRunner.AndAsync("the interface remains fully functional", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Landscape orientation support")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Landscape orientation support")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "viewport")]
        public async System.Threading.Tasks.Task LandscapeOrientationSupport()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "viewport"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Landscape orientation support", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 110
    await testRunner.GivenAsync("I am on a mobile device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 111
    await testRunner.WhenAsync("I rotate to landscape orientation", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 112
    await testRunner.ThenAsync("the chat layout adjusts appropriately", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 113
    await testRunner.AndAsync("the input remains accessible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
    await testRunner.AndAsync("content is not cut off", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
    await testRunner.AndAsync("the interface remains usable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Smooth performance on mobile devices")]
        [Xunit.TraitAttribute("FeatureTitle", "Mobile-Responsive Chat Interface (Story 3-6)")]
        [Xunit.TraitAttribute("Description", "Smooth performance on mobile devices")]
        [Xunit.TraitAttribute("Category", "ui")]
        [Xunit.TraitAttribute("Category", "mobile")]
        [Xunit.TraitAttribute("Category", "performance")]
        public async System.Threading.Tasks.Task SmoothPerformanceOnMobileDevices()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "mobile",
                    "performance"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Smooth performance on mobile devices", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 118
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 119
    await testRunner.GivenAsync("I am on a mobile device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
    await testRunner.WhenAsync("I interact with the chat interface", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
    await testRunner.ThenAsync("scrolling is smooth at 60fps", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
    await testRunner.AndAsync("touch responses are immediate", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
    await testRunner.AndAsync("the app feels native", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.AndAsync("memory usage is optimized", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Mobile_ResponsiveChatInterfaceStory3_6Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Mobile_ResponsiveChatInterfaceStory3_6Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
